[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Desmos = "4511bacd-46ac-4e41-b5d2-355eeb7547f4"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
QuadraticOptimizer = "e7241e48-3d3b-4ed3-9130-818aaeb8a636"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
